### ISSUE TITLE
When self.mechanisms is None in spf.py it returns an error

### ISSUE THREAD

**Issue by mauroka** [lunarca/pyemailprotectionslib#2]
With some domains where when the Include mechanisms include a strong record, self.mechanisms variable is None in spf.py and it returns an error.
To solve it you must first check in line 34 and 43 that self.mechanisms is not None, like this:
if self.mechanisms:
And then iterate. The code will get like this:

    def get_redirect_domain(self):
        redirect_domain = None
        if self.mechanisms:
            for mechanism in self.mechanisms:
                redirect_mechanism = re.match('redirect=(.*)', mechanism)
                if redirect_mechanism is not None:
                    redirect_domain = redirect_mechanism.group(1)
        return redirect_domain

    def get_include_domains(self):
        include_domains = []
        if self.mechanisms:
            for mechanism in self.mechanisms:
                include_mechanism = re.match('include:(.*)', mechanism)
                if include_mechanism is not None:
                    include_domains.append(include_mechanism.group(1))
        return include_domains

Cheers.
Mauro.

**Comment by lunarca** [comment]
Issue confirmed. Currently working on fix.

**Comment by lunarca** [comment]
Fixed and pushed to master. The fix is also pushed to pypi as 0.8.3.

Thanks for the report!
